systemd/sddm: Fix dbus config filename conflict with lightdm
This fixes the following error while installing sddm and lightdm together.
ERROR: lightdm-1.32.0-r6: trying to overwrite usr/share/dbus-1/system.d/org.freedesktop.DisplayManager.conf owned by sddm-9999_git20240428-r0.

Backported from https://gitlab.alpinelinux.org/alpine/aports/-/commit/e3996ee2af40676e3be4afcc9582ddeaa83c1813

Part-of: https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/6752
[ci:skip-build]: already built successfully in CI