cross/gcc-*: fix conflict with native gcc
Run aportgen again with pmbootstrap MR 2597 to fix the conflict when
installing cross gcc and native gcc at the same time:

  (52/53) Installing gcc-armv7 (14.2.0-r6)
  ERROR: gcc-armv7-14.2.0-r6: trying to overwrite usr/lib/libgcc_s.so.1 owned by libgcc-14.2.0-r6.

[ci:skip-vercheck]: for generated gccs we keep the same pkgrel as in
                    alpine. I'll force a rebuild in BPO after merge (not
		    ideal, but fixing this is rather urgent as cross
		    compilation is otherwise broken in pmOS edge)
[ci:skip-build]: tested locally with gcc-armv7

Part-of: https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/6497