maemo/gconf: restore package from Alpine (!928)
main/gconf was removed upstream in Alpine:
  https://gitlab.alpinelinux.org/alpine/aports/commit/0878ac0f6e3d39cd0a748735c88f825fe9e1b8a5

However, some packages in maemo/ (e.g. libhildon) still depend on it.
This breaks the package parsing in bpo: https://builds.sr.ht/~postmarketos/job/146132
  ERROR: Package 'gconf-dev': Could not find aport, and could not find this package in any APKINDEX!

Add it to maemo/ for now to fix the error.