temp/qt5-qtdeclarative: resurrect (!400)
We need our build of qtdeclarative, otherwise building plasma/kde
components fails on arm with:

ld: /usr/lib/libQt5Quick.so.5.12.3: undefined reference to `QOpenGLFunctions_1_0::versionProfile()@Qt_5'
ld: /usr/lib/libQt5Quick.so.5.12.3: undefined reference to `QOpenGLFunctions_3_2_Core::versionProfile()@Qt_5'

That is, because Alpine's qt5-qtdeclarative is built against a
qt5-qtbase version, where the opengl version is not changed to
opengl es2, like it is done in pmaports.

Related: #270