*/*: replace uboot-tools dependency for u-boot-tools (MR 2141)
uboot-tools is provided by u-boot-tools but sometimes apk still gets
confused. This change prevents errors such as

pine64-pinephone:~$ sudo apk upgrade --verbose
WARNING: Failed to perform initial self-upgrade, continuing with full upgrade.
ERROR: unable to select packages:
  uboot-tools (virtual):
	    provided by: u-boot-tools
			    required by: device-pine64-pinephone-0.25-r1[uboot-tools]
[ci:ignore-count]
[ci:skip-build]: already built in CI successfully