soc-qcom-sdm845: fix dependency typo of -vulkan subpackage (MR 3495)
Fixes:

  ERROR: unable to select packages:
    mesa-vulkan-freedreeno (no such package):
      required by: soc-qcom-sdm845-vulkan-9-r0[mesa-vulkan-freedreeno]

Reference: https://pkgs.alpinelinux.org/package/edge/main/aarch64/mesa-vulkan-freedreno