linux-alcatel-ttab: fix missing deps
As many other downstream kernels, this needs to depend on linux-headers
to fix:

In file included from /home/pmos/build/src/android_kernel_alcatel_ttab-1795ea3c237773d32616954a03738d67d209a8d7/scripts/sortextable.c:31:
/home/pmos/build/src/android_kernel_alcatel_ttab-1795ea3c237773d32616954a03738d67d209a8d7/tools/include/tools/be_byteshift.h:4:10: fatal error: linux/types.h: No such file or directory
    4 | #include <linux/types.h>
      |          ^~~~~~~~~~~~~~~

It also needs xz:

/home/pmos/build/src/android_kernel_alcatel_ttab-1795ea3c237773d32616954a03738d67d209a8d7/scripts/xz_wrap.sh: exec: line 23: xz: not found

Related: https://builds.sr.ht/~postmarketos/job/1477748#task-pmbootstrap_build-583

Part-of: https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/6446
[ci:skip-build]: already built successfully in CI