samsung-j5: solve potential filename conflict (MR 4438)
ERROR: the source file 'WCNSS_qcom_wlan_nv.bin' has different checksums in the following files:
- device/testing/firmware-samsung-j5/APKBUILD: 742ee81d034116cf1ecdfae5f75495e6b10ce5be0c2a999b6c8a2c161b1da8b48d6810d5405edb8c829b96fdf75e45a565c74963c76d1bca4aaedf28572fa91f
...

Fix this by setting a different target filename in the package you modified:
https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#source

[ci:skip-build]: already built successfully in CI