temp/mesa-git: upgrade to 0_git20191223 (!826)
Build src/git_sha1.h early to avoid build failure:

../src/vulkan/overlay-layer/overlay.cpp:31:10: fatal error: git_sha1.h: No such file or directory
   31 | #include "git_sha1.h"
      |          ^~~~~~~~~~~~